name: "SpecSentinel"
description: "Compare Flutter widget specs against Figma"
author: "SpecSentinel"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github-token:
    description: "GitHub token (for future use such as commenting)"
    required: true
  figma-token:
    description: "Figma personal access token"
    required: true
  mode:
    description: "Comparison mode (static only for now)"
    required: false
  source:
    description: "Explicit Dart source path for static mode"
    required: false
  source-root:
    description: "Root directory to search for Dart sources (default: lib)"
    required: false
  output-dir:
    description: "Directory where the Flutter test writes screenName.json"
    required: false
  working-directory:
    description: "Directory to run commands in"
    required: false
branding:
  color: "blue"
  icon: "eye"
