name: "SpecSentinel"
description: "Compare UI specs against Figma (static mode, stack-agnostic)"
author: "SpecSentinel"
runs:
  using: "composite"
  steps:
    - name: Parse figma-spec comment
      id: parse
      shell: bash
      run: |
        body=$(jq -r '.comment.body // ""' "$GITHUB_EVENT_PATH")
        if [[ "$body" =~ ^[[:space:]]*figma-spec:[[:space:]]*([A-Za-z0-9_-]+)[[:space:]]+https://www\.figma\.com/file/([A-Za-z0-9]+)[^?[:space:]]*\?node-id=([A-Za-z0-9:-]+) ]]; then
          echo "screen=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          echo "fileKey=${BASH_REMATCH[2]}" >> "$GITHUB_OUTPUT"
          echo "nodeId=${BASH_REMATCH[3]}" >> "$GITHUB_OUTPUT"
        else
          echo "No figma-spec line found in comment, skipping."
          exit 78
        fi

    - name: Run SpecSentinel (static)
      shell: bash
      env:
        FIGMA_TOKEN: ${{ inputs.figma-token }}
        SCREEN: ${{ steps.parse.outputs.screen }}
        FILE_KEY: ${{ steps.parse.outputs.fileKey }}
        NODE_ID: ${{ steps.parse.outputs.nodeId }}
        EXTRA_ARGS: ${{ inputs.extra-args }}
      run: |
        set -euo pipefail
        cmd=(npx --yes specsentinel check
          --screen "${SCREEN}"
          --figma-file "${FILE_KEY}"
          --figma-node "${NODE_ID}"
          --mode static
          --output-dir "${{ inputs.output-dir }}"
          --cwd "${{ inputs.working-directory }}"
        )
        if [[ -n "${INPUT_SOURCE_ROOT}" ]]; then
          cmd+=("--source-root" "${INPUT_SOURCE_ROOT}")
        fi
        if [[ -n "${INPUT_SOURCE}" ]]; then
          cmd+=("--source" "${INPUT_SOURCE}")
        fi
        if [[ -n "${EXTRA_ARGS}" ]]; then
          # shellcheck disable=SC2206
          extra=( ${EXTRA_ARGS} )
          cmd+=("${extra[@]}")
        fi
        "${cmd[@]}"
      env:
        INPUT_SOURCE_ROOT: ${{ inputs.source-root }}
        INPUT_SOURCE: ${{ inputs.source }}
inputs:
  figma-token:
    description: "Figma personal access token"
    required: true
  output-dir:
    description: "Directory where the spec JSON is written (default: build/specsentinel)"
    required: false
    default: "build/specsentinel"
  working-directory:
    description: "Directory to run commands in"
    required: false
    default: "."
  source:
    description: "Explicit Dart source path for static mode"
    required: false
  source-root:
    description: "Root directory to search for Dart sources (default: lib)"
    required: false
    default: "lib"
  extra-args:
    description: "Additional args to pass through to the CLI (space-separated)"
    required: false
branding:
  color: "blue"
  icon: "eye"
